on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  lint:
    uses: medcomdk/fhir-publishing/.github/workflows/fsh-lint.yaml@main